#!/bin/bash

echo -ne "Setting MySQL root password... "

echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pnetlab'" | mysql --host=localhost --user=root &> /dev/null
if [ $? -ne 0 ]; then
	echo -e "warning: Root password of mysql is already set"
fi



